version: '3.8'

services:
  compression-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compression-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GO_ENV=production
    restart: unless-stopped
    networks:
      - compression-network
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  compression-network:
    driver: bridge

# Volume for persistent data (if needed)
volumes:
  compression-data: